//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Mini_Project_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_tbl()
        {
            this.Submission_tbl = new HashSet<Submission_tbl>();
        }
    
        public int St_Id { get; set; }
        public string St_Name { get; set; }
        public string St_Father_Name { get; set; }
        public System.DateTime St_DOB { get; set; }
        public string St_Phone_No { get; set; }
        public string St_Address { get; set; }
        [Required(ErrorMessage = "Email Required")]
        [EmailAddress(ErrorMessage = "Invalid Email")]
        public string St_Email { get; set; }
        [Required(ErrorMessage = "Password Required")]
        public string St_Password { get; set; }
        public string St_Confirm_Password { get; set; }
        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submission_tbl> Submission_tbl { get; set; }
    }
}
